### ISSUE TITLE
1.12.2 deprecation warning

### ISSUE THREAD

**Issue by PhanaticD** [BenWoodworth/FastCraft#124]
```
[14:58:42 WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[14:58:42 WARN]:        at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:26)
[14:58:42 WARN]:        at co.kepler.fastcraftplus.util.RecipeUtil.cloneRecipe(RecipeUtil.java:287)
[14:58:42 WARN]:        at co.kepler.fastcraftplus.recipes.FastRecipe.getRecipe(FastRecipe.java:57)
[14:58:42 WARN]:        at co.kepler.fastcraftplus.recipes.FastRecipe.craft(FastRecipe.java:220)
[14:58:42 WARN]:        at co.kepler.fastcraftplus.craftgui.buttons.GUIButtonRecipe.onClick(GUIButtonRecipe.java:118)
[14:58:42 WARN]:        at co.kepler.fastcraftplus.api.gui.GUI$GUIListener.onInventoryClick(GUI.java:207)
[14:58:42 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1274.execute(Unknown Source)
[14:58:42 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[14:58:42 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[14:58:42 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:58:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
[14:58:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
[14:58:42 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1980)
[14:58:42 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[14:58:42 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[14:58:42 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[14:58:42 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:58:42 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:58:42 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[14:58:42 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[14:58:42 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[14:58:42 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[14:58:42 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[14:58:42 WARN]:        at java.lang.Thread.run(Thread.java:748)

```

**Comment by BenWoodworth** [comment]
What server version are you using?

**Comment by PhanaticD** [comment]
1.12.2

**Comment by BenWoodworth** [comment]
Do you have a more specific version? I'm testing on this with no problem:
```
CraftBukkit version git-Spigot-549c1fa-45c8386 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

**Comment by PhanaticD** [comment]
latest paperspigot, see this https://github.com/PaperMC/Paper/commit/ece3333123a97990408be5392361e288b63835ba

**Comment by BenWoodworth** [comment]
Alright, thanks! This will be fixed in the next release.
