### ISSUE TITLE
Deprecated method

### ISSUE THREAD

**Issue by MrSpock78** [BenWoodworth/FastCraft#127]
## Description
Spam in console everytime a player craft something with Fastcraft+(0.27.2) since Paper(1271).
https://github.com/PaperMC/Paper/commit/ece3333123a97990408be5392361e288b63835ba

## Output/Files
```
[12:21:53] [Server thread/WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[12:21:53] [Server thread/WARN]:     at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:26)
[12:21:53] [Server thread/WARN]:     at co.kepler.fastcraftplus.util.RecipeUtil.cloneRecipe(RecipeUtil.java:287)
[12:21:53] [Server thread/WARN]:     at co.kepler.fastcraftplus.recipes.FastRecipe.getRecipe(FastRecipe.java:57)
[12:21:53] [Server thread/WARN]:     at co.kepler.fastcraftplus.recipes.FastRecipe.craft(FastRecipe.java:220)
[12:21:53] [Server thread/WARN]:     at co.kepler.fastcraftplus.craftgui.buttons.GUIButtonRecipe.onClick(GUIButtonRecipe.java:118)
[12:21:53] [Server thread/WARN]:     at co.kepler.fastcraftplus.api.gui.GUI$GUIListener.onInventoryClick(GUI.java:205)
[12:21:53] [Server thread/WARN]:     at sun.reflect.GeneratedMethodAccessor422.invoke(Unknown Source)
[12:21:53] [Server thread/WARN]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:21:53] [Server thread/WARN]:     at java.lang.reflect.Method.invoke(Method.java:498)
[12:21:53] [Server thread/WARN]:     at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:120)
[12:21:53] [Server thread/WARN]:     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:21:53] [Server thread/WARN]:     at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36)
[12:21:53] [Server thread/WARN]:     at us.Myles.PWP.TransparentListeners.PWPTimedRegisteredListener.callEvent(PWPTimedRegisteredListener.java:30)
[12:21:53] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
[12:21:53] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
[12:21:53] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1980)
[12:21:53] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[12:21:53] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[12:21:53] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[12:21:53] [Server thread/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:21:53] [Server thread/WARN]:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:21:53] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:21:53] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[12:21:53] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[12:21:53] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[12:21:53] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[12:21:53] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:748)
```

## Server Details
- FastCraft Version: 0.27.2
- Server Version: PAPER 1.12.2 (1271)

**Comment by BenWoodworth** [comment]
Fixed in v2.0 :smile:
