### ISSUE TITLE
AssertionError: TRAP (itemStack = ItemStack{AIR x 0}; amount = 1)

### ISSUE THREAD

**Issue by BenWoodworth** [BenWoodworth/FastCraft#182]
## Description
https://www.spigotmc.org/threads/fastcraft-craft-items-in-one-click-1-7-1-16.133803/page-50#post-3875563

[DrBot](https://www.spigotmc.org/members/drbot.460148/):
> I got this error on Purpur-651 and Fastcraft 3.2.5
> https://hasteb.in/elovazok.cs
> I don't know what caused it or how to reproduce it. I just looked into my console an saw that errors were being thrown. 

https://github.com/BenWoodworth/FastCraft/blob/v3.2.5/fastcraft-bukkit/bukkit-1.7/src/main/kotlin/net/benwoodworth/fastcraft/bukkit/world/BukkitFcItemStack_1_7.kt#L72

## Server Details
- Server: [Purpur-651](https://ci.pl3x.net/job/Purpur/651/) (1.16.1)
- FastCraft: v3.2.5

## Errors
```
[Sun, 12. Jul 2020 07:50:40 EDT] Share this with Kepler:
[Sun, 12. Jul 2020 07:50:40 EDT] - itemStack = ItemStack{AIR x 0}
[Sun, 12. Jul 2020 07:50:40 EDT] - amount = 1
[Sun, 12. Jul 2020 07:50:40 EDT] java.lang.AssertionError: TRAP
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.ItemStack.checkEmpty(ItemStack.java:156)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.ItemStack.setCount(ItemStack.java:991)
[Sun, 12. Jul 2020 07:50:40 EDT]     at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftItemStack.setAmount(CraftItemStack.java:149)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.benwoodworth.fastcraft.bukkit.world.BukkitFcItemStack_1_7$Factory.copyItem(BukkitFcItemStack_1_7.kt:72)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.benwoodworth.fastcraft.crafting.model.ItemAmounts.asKey(ItemAmounts.kt:22)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.benwoodworth.fastcraft.crafting.model.ItemAmounts.get(ItemAmounts.kt:28)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.benwoodworth.fastcraft.crafting.model.FastCraftRecipe.canCraft(FastCraftRecipe.kt:41)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.benwoodworth.fastcraft.crafting.model.FastCraftGuiModel.craftRecipe(FastCraftGuiModel.kt:65)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter$RecipeButtonListener.onCraft(FastCraftGuiPresenter.kt:170)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.benwoodworth.fastcraft.crafting.view.buttons.RecipeButtonView$ButtonListener$onClick$action$1.invoke(RecipeButtonView.kt:140)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.benwoodworth.fastcraft.crafting.view.buttons.RecipeButtonView$ButtonListener$onClick$action$1.invoke(RecipeButtonView.kt:134)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.benwoodworth.fastcraft.crafting.view.buttons.RecipeButtonView$ButtonListener.onClick(RecipeButtonView.kt:149)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.benwoodworth.fastcraft.bukkit.gui.BukkitFcGui_1_7$InventoryListener.onInventoryClick(BukkitFcGui_1_7.kt:106)
[Sun, 12. Jul 2020 07:50:40 EDT]     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[Sun, 12. Jul 2020 07:50:40 EDT]     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[Sun, 12. Jul 2020 07:50:40 EDT]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[Sun, 12. Jul 2020 07:50:40 EDT]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2479)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1204)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1197)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1173)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1017)
[Sun, 12. Jul 2020 07:50:40 EDT]     at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[Sun, 12. Jul 2020 07:50:40 EDT]     at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by BenWoodworth** [comment]
Related:

https://www.spigotmc.org/threads/fastcraft-craft-items-in-one-click-1-7-1-16.133803/page-46#post-3775853
[WarnDangerous](https://www.spigotmc.org/members/warndangerous.85641/):
> Hello,
> Here is an error from latest version on paper 1.15.2 build 212 :)
> https://pastebin.com/dacmq3vT

https://github.com/BenWoodworth/FastCraft/commit/77d0abaf3844fd52e6f297342babefbb2c60828e
