### ISSUE TITLE
Error: Share this with Kepler

### ISSUE THREAD

**Issue by SrBedrock** [BenWoodworth/FastCraft#185]
## Description

I found this error on the console, I believe it is due to a chest with name and custom lore. (contains color code)

## Server Details
- Server: 1.16.1 git-Tuinity-"8608126"
- FastCraft: v3.2.2

## Errors

```
[00:28:02 WARN]: Share this with Kepler:
[00:28:02 WARN]: - itemStack = ItemStack{AIR x 0, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name=Baú de Proteção, lore=[O primeiro baú colocado no, servidor criará uma proteção, de 5x5 para cada lado do baú!]}}
[00:28:02 WARN]: - amount = 1
[00:28:02 WARN]: [FastCraft] Task #40153879 for FastCraft v3.2.2 generated an exception
java.lang.AssertionError: TRAP
at net.minecraft.server.v1_16_R1.ItemStack.checkEmpty(ItemStack.java:156) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.ItemStack.setCount(ItemStack.java:970) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftItemStack.setAmount(CraftItemStack.java:149) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.benwoodworth.fastcraft.bukkit.world.BukkitFcItemStack_1_7$Factory.copyItem(BukkitFcItemStack_1_7.kt:72) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.ItemAmounts.asKey(ItemAmounts.kt:22) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.ItemAmounts.get(ItemAmounts.kt:28) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.FastCraftRecipe.canCraft(FastCraftRecipe.kt:41) ~[?:?]
at net.benwoodworth.fastcraft.crafting.view.buttons.RecipeButtonView.update(RecipeButtonView.kt:34) ~[?:?]
at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter.updateRecipes(FastCraftGuiPresenter.kt:47) ~[?:?]
at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter.updatePage(FastCraftGuiPresenter.kt:58) ~[?:?]
at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter.access$updatePage(FastCraftGuiPresenter.kt:9) ~[?:?]
at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter$ModelListener.onRecipesChange(FastCraftGuiPresenter.kt:74) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.FastCraftGuiModel$CraftableRecipeFinderListener.onNewRecipesLoaded(FastCraftGuiModel.kt:54) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.CraftableRecipeFinder$loadRecipes$1$2.invoke(CraftableRecipeFinder.kt:77) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.CraftableRecipeFinder$loadRecipes$1$2.invoke(CraftableRecipeFinder.kt:21) ~[?:?]
at net.benwoodworth.fastcraft.bukkit.server.BukkitFcTask_1_7$runnable$1.run(BukkitFcTask_1_7.kt:20) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1356) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1269) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at java.lang.Thread.run(Thread.java:832) [?:?]
[00:28:03 WARN]: Share this with Kepler:
[00:28:03 WARN]: - itemStack = ItemStack{AIR x 0, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name=Baú de Proteção, lore=[O primeiro baú colocado no, servidor criará uma proteção, de 5x5 para cada lado do baú!]}}
[00:28:03 WARN]: - amount = 1
[00:28:03 WARN]: [FastCraft] Task #40153879 for FastCraft v3.2.2 generated an exception
java.lang.AssertionError: TRAP
at net.minecraft.server.v1_16_R1.ItemStack.checkEmpty(ItemStack.java:156) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.ItemStack.setCount(ItemStack.java:970) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftItemStack.setAmount(CraftItemStack.java:149) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.benwoodworth.fastcraft.bukkit.world.BukkitFcItemStack_1_7$Factory.copyItem(BukkitFcItemStack_1_7.kt:72) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.ItemAmounts.asKey(ItemAmounts.kt:22) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.ItemAmounts.get(ItemAmounts.kt:28) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.FastCraftRecipe.canCraft(FastCraftRecipe.kt:41) ~[?:?]
at net.benwoodworth.fastcraft.crafting.view.buttons.RecipeButtonView.update(RecipeButtonView.kt:34) ~[?:?]
at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter.updateRecipes(FastCraftGuiPresenter.kt:47) ~[?:?]
at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter.updatePage(FastCraftGuiPresenter.kt:58) ~[?:?]
at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter.access$updatePage(FastCraftGuiPresenter.kt:9) ~[?:?]
at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter$ModelListener.onRecipesChange(FastCraftGuiPresenter.kt:74) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.FastCraftGuiModel$CraftableRecipeFinderListener.onNewRecipesLoaded(FastCraftGuiModel.kt:54) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.CraftableRecipeFinder$loadRecipes$1$2.invoke(CraftableRecipeFinder.kt:77) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.CraftableRecipeFinder$loadRecipes$1$2.invoke(CraftableRecipeFinder.kt:21) ~[?:?]
at net.benwoodworth.fastcraft.bukkit.server.BukkitFcTask_1_7$runnable$1.run(BukkitFcTask_1_7.kt:20) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1356) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1269) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at java.lang.Thread.run(Thread.java:832) [?:?]
[00:28:03 WARN]: Share this with Kepler:
[00:28:03 WARN]: - itemStack = ItemStack{AIR x 0, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name=Baú de Proteção, lore=[O primeiro baú colocado no, servidor criará uma proteção, de 5x5 para cada lado do baú!]}}
[00:28:03 WARN]: - amount = 1
[00:28:03 WARN]: [FastCraft] Task #40153879 for FastCraft v3.2.2 generated an exception
java.lang.AssertionError: TRAP
at net.minecraft.server.v1_16_R1.ItemStack.checkEmpty(ItemStack.java:156) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.ItemStack.setCount(ItemStack.java:970) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftItemStack.setAmount(CraftItemStack.java:149) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.benwoodworth.fastcraft.bukkit.world.BukkitFcItemStack_1_7$Factory.copyItem(BukkitFcItemStack_1_7.kt:72) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.ItemAmounts.asKey(ItemAmounts.kt:22) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.ItemAmounts.get(ItemAmounts.kt:28) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.FastCraftRecipe.canCraft(FastCraftRecipe.kt:41) ~[?:?]
at net.benwoodworth.fastcraft.crafting.view.buttons.RecipeButtonView.update(RecipeButtonView.kt:34) ~[?:?]
at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter.updateRecipes(FastCraftGuiPresenter.kt:47) ~[?:?]
at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter.updatePage(FastCraftGuiPresenter.kt:58) ~[?:?]
at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter.access$updatePage(FastCraftGuiPresenter.kt:9) ~[?:?]
at net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter$ModelListener.onRecipesChange(FastCraftGuiPresenter.kt:74) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.FastCraftGuiModel$CraftableRecipeFinderListener.onNewRecipesLoaded(FastCraftGuiModel.kt:54) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.CraftableRecipeFinder$loadRecipes$1$2.invoke(CraftableRecipeFinder.kt:77) ~[?:?]
at net.benwoodworth.fastcraft.crafting.model.CraftableRecipeFinder$loadRecipes$1$2.invoke(CraftableRecipeFinder.kt:21) ~[?:?]
at net.benwoodworth.fastcraft.bukkit.server.BukkitFcTask_1_7$runnable$1.run(BukkitFcTask_1_7.kt:20) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1356) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1269) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Tuinity-"8608126"]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by SrBedrock** [comment]
I will update the plugin to the latest version and see if the error occurs again.

**Comment by BenWoodworth** [comment]
If it's still an issue, could you try this build?
https://974-53271895-gh.circle-artifacts.com/0/artifacts/FastCraft.jar

**Comment by SrBedrock** [comment]
After updating the version I was unable to reproduce the error.
