### ISSUE TITLE
bug or incompatibility with crazycrates plugin.

### ISSUE THREAD

**Issue by patrick323** [BenWoodworth/FastCraft#216]
## Description
When opening the fastcraft plugin in the workbench, errors randomly appear in the console when building certain materials, which I don't know which caused these errors.

## Errors
 ```
[23:46:24 ERROR]: Could not pass event CraftItemEvent to CrazyCrates v1.21.3-330
java.lang.AbstractMethodError: Receiver class net.benwoodworth.fastcraft.bukkit.recipe.CraftingInventoryViewFactory_1_14$CustomCraftingInventory does not define or inherit an implementation of the resolved method 'abstract org.bukkit.inventory.InventoryHolder getHolder(boolean)' of interface org.bukkit.inventory.Inventory.
        at CrazyCrates-1.21.3-330.jar/com.badbones69.crazycrates.listeners.crates.types.CosmicCrateListener.onPrizeReceive(CosmicCrateListener.java:61) ~[CrazyCrates-1.21.3-330.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1221.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at FastCraft-3.2.13.jar/net.benwoodworth.fastcraft.bukkit.recipe.FcCraftingRecipePrepared_Bukkit_1_7.craft(FcCraftingRecipePrepared_Bukkit_1_7.kt:51) ~[FastCraft-3.2.13.jar:?]
        at FastCraft-3.2.13.jar/net.benwoodworth.fastcraft.crafting.model.FastCraftGuiModel.craftRecipe(FastCraftGuiModel.kt:91) ~[FastCraft-3.2.13.jar:?]
        at FastCraft-3.2.13.jar/net.benwoodworth.fastcraft.crafting.presenter.FastCraftGuiPresenter$RecipeButtonListener.onCraft(FastCraftGuiPresenter.kt:190) ~[FastCraft-3.2.13.jar:?]
        at FastCraft-3.2.13.jar/net.benwoodworth.fastcraft.crafting.view.buttons.RecipeButtonView$ButtonListener$onClick$action$1.invoke(RecipeButtonView.kt:140) ~[FastCraft-3.2.13.jar:?]
        at FastCraft-3.2.13.jar/net.benwoodworth.fastcraft.crafting.view.buttons.RecipeButtonView$ButtonListener$onClick$action$1.invoke(RecipeButtonView.kt:140) ~[FastCraft-3.2.13.jar:?]
        at FastCraft-3.2.13.jar/net.benwoodworth.fastcraft.crafting.view.buttons.RecipeButtonView$ButtonListener.onClick(RecipeButtonView.kt:149) ~[FastCraft-3.2.13.jar:?]
        at FastCraft-3.2.13.jar/net.benwoodworth.fastcraft.bukkit.gui.FcGui_Bukkit_1_7$InventoryListener.onInventoryClick(FcGui_Bukkit_1_7.kt:113) ~[FastCraft-3.2.13.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3224) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
![image](https://github.com/user-attachments/assets/d030067e-ba81-4fa4-a8e7-7f15cf0ee691)

## Server Details
- Server: Paper version 1.21.1-132-ver/1.21.1@b48403b 
- FastCraft version 3.2.13
- CrazyCrates version 1.21.3-330

**Comment by patrick323** [comment]
any news?
